export interface Startup {
  id: string;
  name: string;
  sector: string;
  stage: string;
  location: string;
  website: string;
  description: string;
  tags: string[];
}

export const startups: Startup[] = [
  {
    id: "1",
    name: "Lumina AI",
    sector: "AI",
    stage: "Series A",
    location: "US",
    website: "https://lumina.ai",
    description: "Next-gen computer vision for autonomous manufacturing.",
    tags: ["Computer Vision", "Manufacturing", "Enterprise"],
  },
  {
    id: "2",
    name: "FinFlow",
    sector: "Fintech",
    stage: "Seed",
    location: "Europe",
    website: "https://finflow.io",
    description: "Real-time treasury management for modern startups.",
    tags: ["Treasury", "SaaS", "B2B"],
  },
  {
    id: "3",
    name: "EcoScale",
    sector: "SaaS",
    stage: "Pre-seed",
    location: "India",
    website: "https://ecoscale.eco",
    description: "Carbon footprint tracking for supply chains.",
    tags: ["Sustainability", "ClimateTech", "Analytics"],
  },
  {
    id: "4",
    name: "CipherHealth",
    sector: "Healthtech",
    stage: "Series B",
    location: "US",
    website: "https://cipherhealth.com",
    description: "Secure data exchange for healthcare providers.",
    tags: ["HIPAA", "Data Privacy", "Infrastructure"],
  },
  {
    id: "5",
    name: "QuantumLeap",
    sector: "DeepTech",
    stage: "Seed",
    location: "UK",
    website: "https://quantumleap.tech",
    description: "Benchmarking tools for quantum computing algorithms.",
    tags: ["Quantum", "Developer Tools", "AI"],
  },
  {
    id: "6",
    name: "Aetheria",
    sector: "Entertainment",
    stage: "Seed",
    location: "Japan",
    website: "https://aetheria.jp",
    description: "Immersive VR experiences for remote collaboration.",
    tags: ["VR", "Remote Work", "Metaverse"],
  },
  {
    id: "7",
    name: "SwiftPay",
    sector: "Fintech",
    stage: "Series A",
    location: "India",
    website: "https://swiftpay.in",
    description: "One-click checkout for emerging markets.",
    tags: ["Payments", "Ecommerce", "Fintech"],
  },
  {
    id: "8",
    name: "NeuralNodes",
    sector: "AI",
    stage: "Pre-seed",
    location: "US",
    website: "https://neuralnodes.ai",
    description: "Distributed training infrastructure for large language models.",
    tags: ["LLM", "Infrastructure", "GPU"],
  },
  {
    id: "9",
    name: "BioBot",
    sector: "Healthtech",
    stage: "Seed",
    location: "Israel",
    website: "https://biobot.ai",
    description: "Robotic automation for diagnostic laboratories.",
    tags: ["Robotics", "Diagnostics", "BioTech"],
  },
  {
    id: "10",
    name: "OrbitFlow",
    sector: "SaaS",
    stage: "Series B",
    location: "Germany",
    website: "https://orbitflow.de",
    description: "Project management for space exploration startups.",
    tags: ["SpaceTech", "SaaS", "Management"],
  },
  {
    id: "11",
    name: "Veritas AI",
    sector: "AI",
    stage: "Series A",
    location: "US",
    website: "https://veritas.ai",
    description: "Ethical AI auditing and bias detection platforms.",
    tags: ["Ethics", "AI", "Governance"],
  },
  {
    id: "12",
    name: "PulseGrid",
    sector: "Energy",
    stage: "Seed",
    location: "Norway",
    website: "https://pulsegrid.io",
    description: "Smart grid management for renewable energy storage.",
    tags: ["Energy", "Sustainability", "IoT"],
  },
  {
    id: "13",
    name: "NanoMed",
    sector: "Healthtech",
    stage: "Series C",
    location: "Switzerland",
    website: "https://nanomed.ch",
    description: "Targeted drug delivery using nanotechnology.",
    tags: ["Nano", "BioTech", "Pharma"],
  },
  {
    id: "14",
    name: "CloudForge",
    sector: "SaaS",
    stage: "Seed",
    location: "Canada",
    website: "https://cloudforge.dev",
    description: "Automated DevOps for hybrid cloud environments.",
    tags: ["DevOps", "Infrastructure", "Cloud"],
  },
  {
    id: "15",
    name: "StellarPay",
    sector: "Fintech",
    stage: "Series A",
    location: "Brazil",
    website: "https://stellarpay.br",
    description: "Cross-border payments for Latin American merchants.",
    tags: ["Payments", "Fintech", "LatAm"],
  },
  {
    id: "16",
    name: "AquaSense",
    sector: "Sustainability",
    stage: "Pre-seed",
    location: "Australia",
    website: "https://aquasense.au",
    description: "AI-powered water leak detection for smart cities.",
    tags: ["IoT", "Water", "SmartCity"],
  },
  {
    id: "17",
    name: "SynthFlow",
    sector: "AI",
    stage: "Seed",
    location: "US",
    website: "https://synthflow.ai",
    description: "Generative AI for automated customer support workflows.",
    tags: ["LLM", "SaaS", "AI"],
  },
  {
    id: "18",
    name: "NovaRetail",
    sector: "Retail",
    stage: "Series B",
    location: "UK",
    website: "https://novaretail.com",
    description: "Checkout-free retail technology for grocery chains.",
    tags: ["Computer Vision", "Retail", "Ecommerce"],
  },
  {
    id: "19",
    name: "SafeGuard",
    sector: "Cybersecurity",
    stage: "Series A",
    location: "US",
    website: "https://safeguard.io",
    description: "Real-time threat detection for remote workforces.",
    tags: ["Security", "RemoteWork", "B2B"],
  },
  {
    id: "20",
    name: "TerraFarm",
    sector: "Sustainability",
    stage: "Seed",
    location: "Netherlands",
    website: "https://terrafarm.nl",
    description: "Vertical farming infrastructure for urban environments.",
    tags: ["AgTech", "Sustainability", "Food"],
  },
  {
    id: "21",
    name: "BlockStream",
    sector: "Web3",
    stage: "Series C",
    location: "US",
    website: "https://blockstream.com",
    description: "Bitcoin-based financial infrastructure and sidechains.",
    tags: ["Bitcoin", "Blockchain", "Infrastructure"],
  },
  {
    id: "22",
    name: "DeepLogic",
    sector: "AI",
    stage: "Series B",
    location: "France",
    website: "https://deeplogic.ai",
    description: "Interpretable machine learning for industrial sectors.",
    tags: ["Industrial", "AI", "Analytics"],
  },
  {
    id: "23",
    name: "ZenithSpace",
    sector: "DeepTech",
    stage: "Seed",
    location: "US",
    website: "https://zenithspace.com",
    description: "Microsatellite propulsion systems for smallsats.",
    tags: ["Space", "DeepTech", "Propulsion"],
  },
  {
    id: "24",
    name: "FlexHealth",
    sector: "Healthtech",
    stage: "Series A",
    location: "India",
    website: "https://flexhealth.in",
    description: "Personalized nutrition plans driven by blood markers.",
    tags: ["Health", "BioTech", "personalized"],
  },
  {
    id: "25",
    name: "OmniLog",
    sector: "SaaS",
    stage: "Series B",
    location: "US",
    website: "https://omnilog.io",
    description: "Logistics orchestration platform for global shipping.",
    tags: ["Logistics", "SaaS", "SupplyChain"],
  }
];
